<?php
/**
* copyright            : (C) 2001-2010 Advanced Internet Designs Inc.
* email                : forum@prohost.org
* $Id$
*
* This program is free software; you can redistribute it and/or modify it
* under the terms of the GNU General Public License as published by the
* Free Software Foundation; version 2 of the License.
**/

/* Needed by admapprove_avatar.php, so that avatar approval/decline can be sent in the appropriate languge. */

$GLOBALS['approved_avatar_title'] = 'Su avatar personalizado fue aprobado.';
$GLOBALS['approved_avatar_msg'] = 'Su avatar fue aprobado por el administrador. A partir de ahora debería aparecer como su avatar en todos sus mensajes. Si no lo ve, o ve su antiguo avatar, es porque su navegador ha guardado la página en la caché. Pruebe a recargar la página una o dos veces, en la mayoría de los casos esto resuelve el problema.';
$GLOBALS['unapproved_avatar_title'] = 'Su avatar personalizado ha sido rechazado.';
$GLOBALS['unapproved_avatar_msg'] = 'El administrador no aprobó su avatar. En la mayoría de los casos esto significa que su avatar era demasiado grande (tamaño y/o peso) o que tenía un contenido inapropiado. Si desea más información acerca del motivo del rechazo de su avatar, póngase en contacto con el administrador.';
?>